#!/usr/bin/env bash

: "${PWTIMEOUT:=600}"
PATH=/mariadb/bin:$PATH
args=( -P 4000 -u root --protocol=tcp --prompt='TiDB (\u) [\d]>\ ' -A )
args+=( "$@" )
err=0


t(){ tput -Txterm-256color "$@"; }

red=$(t setaf 1)
reset=$(t sgr0)
msg="

  ${red}            ▄▄            ${reset}
  ${red}         ▄▟████▙▖         ${reset}
  ${red}      ▗▟██████████▄▖      ${reset}
  ${red}   ▗▄██████▀▘▀▜██████▄▖   ${reset}
  ${red}▗▄██████▛▀      ▀██████▙▄ ${reset}
  ${red}█████▛▀        ▄▟█████████${reset}         $(t bold; t setaf 4)Welcome to TiDB!$reset
  ${red}████▌        ▄██████▀▐████${reset}
  ${red}████▌        █████▀  ▐████${reset}
  ${red}████▌ ▗▟▌    ████▌   ▐████${reset}     For TiDB Documentation, see
  ${red}████▌▟██▌    ████▌   ▐████${reset}      https://pingcap.com/docs/
  ${red}████████▌    ████▌   ▐████${reset}
  ${red}████████▌    ████▌   ▐████${reset}              Questions?
  ${red}████████▌    ████▌ ▄▟█████${reset}     Join TiDB Community Slack at
  ${red}▝▜███████▄   ████▙██████▛▘${reset}    https://pingcap.com/tidbslack/
  ${red}   ▀▜██████▙▖█████████▛▀  ${reset}
  ${red}      ▀▜███████████▛▀     ${reset}
  ${red}        ▝▀▜█████▛▀        ${reset}
  ${red}           ▝▀▀▀           ${reset}


Plese enter your TiDB password to log in to a client shell.

"

printf %s\\n "$msg"

if test "${MYSQL_PWD+defined}"; then
    if ! command mysql "${args[@]}"; then
        echo "Incorrect password given."
        err=1
    fi
else
    while true; do
        if ! read -r -s -t "$PWTIMEOUT" -p 'TiDB password: ' password; then
           err=1
           break
        fi
        echo
        command mysql "${args[@]}" --password="$password" && break
    done
fi
echo "Closing connection."
exit "$err"
