#!/usr/bin/env bash

: ${PWTIMEOUT:=600}
args=( -P 3306 -u root --prompt='TiDB (\u) [\d]>\ ' )
args+=( "$@" )
err=0


t(){ tput -Txterm-256color "$@"; }

msg="$(t bold; t setaf 4)Welcome to TiDB!$(t sgr0)

Plese enter your TiDB root password to log in to a client shell.
"

printf %s\\n "$msg"

while true; do
    if ! read -r -s -t "$PWTIMEOUT" -p 'TiDB root password: ' password; then
       err=1
       break
    fi
    command mysql "${args[@]}" --password="$password" && break
done
echo "Closing connection."
exit "$err"
